package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_69"
                param("clientId", "2280447103.1138299994726")
                param("secure:clientSecret", "credentialsJSON:6e14cfcf-ad9a-42d7-bc27-6cc0dbdade59")
                param("displayName", "Slack Test")
                param("secure:token", "credentialsJSON:0f24ef40-f107-4c0b-8bcf-0ddec3c92b25")
                param("providerType", "slackConnection")
            }
        }
    }
}
