package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'NewSettingsRoot'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("NewSettingsRoot")
    name = "new settings root"
    url = "https://github.com/burnasheva/maven_unbalanced_messages"
    branch = "refs/heads/team-city_tests_settings"
    branchSpec = """
        +:refs/heads/(team-city_tests_settings)
        +:refs/heads/(burnasheva/*)
    """.trimIndent()
    authMethod = password {
        userName = "burnasheva"
        password = "credentialsJSON:129576e4-c3ae-4675-a9bf-aaf179c9e8d2"
    }
}))

